server:
  port: 8180


cassandra:
  keyspace: new_k
  host: localhost
  port: 9042
  username: cassandra
  password: cassandra
spring:
  data:
    cassandra:
      local-datacenter: DC1
      keyspace-name: new_k
      contact-points: locahost
      port: 9042
      username: cassandra
      password: cassandra
    mongodb:
      host: localhost
      port: 27017
      database: test
      username: root
      password: example
      authentication-database: test
